class Config:
    BASE_URL = "http://localhost:8000/"
    API_URL = f"{BASE_URL}"
    JWT_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhN2E3NDhkNC05YWE0LTQ0NzMtYTFkMC00ODBlODAyMTc4OGUiLCJleHAiOjE3ODI5ODA1Mjd9.C5rCWRHFEENMNRlofTQ8xs_sFU_dtBCqK9pCdk15A4Y"
    WISHLIST_ID = ""
    ITEM_ID = ""